title:             Kihyun Kim
email:             haha802@naver.com
description:       A Blog Theme by Start Bootstrap
author:            Kihyun Kim
baseurl:           "/main"
url:               "http://hahakhkim.github.io"

# Social Profiles
twitter_username:  
github_username:   hahakhkim
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
